remote_theme: https://github.com/PfeifferChPT/pc-cdn-template
name: "PC-CDN.de"
title: "PC-CDN.de"
subtitle: "DE Theme/Template CDN"
description: "Theme/Template - DE Server | PC-CDN.de" #metadescription
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:title.html
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: blue
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: https://template.pc-cdn.de/content/themes/writr/css/none.css
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
since: 2021
deactivaterelatedposts: true
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
